import type { AllergenCategory, FriendProfile } from "./tabpfn-types";

export const COMMON_ALLERGENS: AllergenCategory[] = [
  {
    id: "peanuts",
    name: "Peanuts & Groundnuts",
    commonNames: ["peanut", "groundnut", "arachis oil", "goober pea", "monkey nut"],
    hiddenDerivatives: [
      "hydrolyzed peanut protein",
      "beer nuts",
      "mixed nuts",
      "artificial flavoring",
      "satay sauce",
      "pad thai sauce",
      "enchilada sauce",
      "marzipan adulterant",
    ],
    icon: "🥜",
    color: "#e11d48", // red
  },
  {
    id: "gluten",
    name: "Gluten & Wheat (Celiac)",
    commonNames: [
      "wheat",
      "barley",
      "rye",
      "malt",
      "spelt",
      "triticale",
      "kamut",
      "semolina",
      "durum",
      "farina",
    ],
    hiddenDerivatives: [
      "maltodextrin (wheat sourced)",
      "hydrolyzed wheat protein",
      "modified food starch",
      "brewer's yeast",
      "soy sauce (wheat-brewed)",
      "malt vinegar",
      "seitan",
      "dextrin",
      "graham flour",
      "bulgur",
      "couscous",
    ],
    icon: "🌾",
    color: "#f59e0b", // amber
  },
  {
    id: "tree_nuts",
    name: "Tree Nuts",
    commonNames: [
      "almond",
      "walnut",
      "cashew",
      "pecan",
      "hazelnut",
      "pistachio",
      "macadamia",
      "brazil nut",
      "pine nut",
    ],
    hiddenDerivatives: [
      "praline",
      "gianduja",
      "nut butter",
      "pesto",
      "mortadella",
      "marzipan",
      "nougat",
      "frangipane",
      "orgeat syrup",
      "nut extracts",
    ],
    icon: "🌰",
    color: "#d97706",
  },
  {
    id: "dairy",
    name: "Dairy & Lactose",
    commonNames: ["milk", "cheese", "butter", "cream", "yogurt", "ghee"],
    hiddenDerivatives: [
      "casein",
      "caseinate",
      "whey",
      "whey protein isolate",
      "lactalbumin",
      "lactoglobulin",
      "curds",
      "caramel coloring (dairy carrier)",
      "nisin",
      "lactic acid starter",
    ],
    icon: "🥛",
    color: "#3b82f6",
  },
  {
    id: "soy",
    name: "Soy & Soya",
    commonNames: ["soy", "soya", "soybean", "edamame", "tofu", "tempeh"],
    hiddenDerivatives: [
      "soy lecithin",
      "hydrolyzed soy protein",
      "textured vegetable protein (TVP)",
      "miso",
      "natto",
      "tamari",
      "shoyu",
      "vegetable broth base",
    ],
    icon: "🌱",
    color: "#10b981",
  },
  {
    id: "shellfish",
    name: "Crustaceans & Molluscs",
    commonNames: [
      "shrimp",
      "prawn",
      "crab",
      "lobster",
      "crawfish",
      "clam",
      "mussel",
      "oyster",
      "scallop",
      "squid",
      "octopus",
    ],
    hiddenDerivatives: [
      "oyster sauce",
      "fish sauce (cross-species)",
      "surimi (imitation crab)",
      "clamato",
      "bouillabaisse",
      "glucosamine",
      "dashi (seafood mix)",
    ],
    icon: "🦐",
    color: "#ef4444",
  },
  {
    id: "sesame",
    name: "Sesame",
    commonNames: ["sesame", "sesame seed", "sesame oil", "sesamum indicum"],
    hiddenDerivatives: [
      "tahini",
      "hummus",
      "halvah",
      "gomashio",
      "za'atar",
      "benne seed",
      "til",
      "furikake",
    ],
    icon: "🥯",
    color: "#8b5cf6",
  },
  {
    id: "eggs",
    name: "Eggs & Albumin",
    commonNames: ["egg", "egg white", "egg yolk", "albumin", "ovalbumin"],
    hiddenDerivatives: [
      "mayonnaise",
      "meringue",
      "lysozyme",
      "lecithin (egg derived)",
      "surimi binder",
      "custard",
      "hollandaise sauce",
    ],
    icon: "🥚",
    color: "#eab308",
  },
];

export const DEFAULT_FRIEND_ALEX: FriendProfile = {
  id: "alex-chen",
  name: "Alex",
  relationship: "Roommate & Best Friend",
  avatar: "🧑‍💻",
  bio: "Alex has severe Celiac Disease (autoimmune reaction to any gluten/wheat traces) and severe peanut anaphylaxis (carries EpiPen). Even micro-traces on shared cutting boards cause acute reactions.",
  emergencyContact: {
    name: "Jordan (Partner)",
    phone: "+1 (555) 234-5678",
    relationship: "Primary Emergency Contact",
  },
  dietaryStyles: [
    "Strict Medical Celiac (Zero Gluten)",
    "Peanut Anaphylactic (EpiPen Carrier)",
    "Lactose Sensitive",
  ],
  customBannedWords: [
    "maltodextrin",
    "brewer's yeast",
    "cross-contamination warning",
    "shared equipment with peanuts",
    "shared fryer with gluten",
    "soy sauce (regular)",
  ],
  rules: [
    {
      allergenId: "gluten",
      allergenName: "Gluten & Wheat",
      severity: "severe",
      notes:
        "Strict Celiac. Zero ppm tolerance. Requires dedicated kitchenware & fryers. No soy sauce unless Tamari certified.",
      strictlyNoSharedEquipment: true,
    },
    {
      allergenId: "peanuts",
      allergenName: "Peanuts",
      severity: "severe",
      notes:
        "Anaphylactic shock risk. Must avoid any peanut oil, satay sauces, or shared bakery lines.",
      strictlyNoSharedEquipment: true,
    },
    {
      allergenId: "dairy",
      allergenName: "Dairy & Lactose",
      severity: "moderate",
      notes:
        "Lactose intolerance. Hard cheeses/aged are tolerable; liquid cream, milk, and soft cheese cause cramps.",
      strictlyNoSharedEquipment: false,
    },
    {
      allergenId: "sesame",
      allergenName: "Sesame",
      severity: "mild",
      notes: "Mild oral itch with raw tahini. Avoid heavy sesame crusts.",
      strictlyNoSharedEquipment: false,
    },
  ],
};
